#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "ESP Cloud Switch"
  https://create.arduino.cc/cloud/things/

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudCounter pc_state_time;
  bool disk_state;
  bool pc_reset_switch;
  bool pc_state;
  bool pc_switch;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

// const int disk_st = 18;
// const int pc_st = 19;
// const int pc_swt = 21;
// const int pc_rst_swt = 5;

#define disk_st 18
#define pc_st 19
#define pc_swt 21
#define pc_rst_swt 5

void setup() {

  pinMode(pc_swt, OUTPUT);
  pinMode(pc_rst_swt, OUTPUT);
  pinMode(pc_st, INPUT);
  pinMode(disk_st, INPUT);
  
  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here
  pc_state = digitalRead(pc_st);
  disk_state = digitalRead(disk_st);
  pc_state_time = pc_state;

}

/*
  Since PcSwitch is READ_WRITE variable, onPcSwitchChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onPcSwitchChange()  {
  // Add your code here to act upon PcSwitch change
  if (pc_switch) {
    digitalWrite(pc_swt, HIGH);
  }
  else {
    digitalWrite(pc_swt, LOW);

  }
}

/*
  Since PcResetSwitch is READ_WRITE variable, onPcResetSwitchChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onPcResetSwitchChange()  {
  // Add your code here to act upon PcResetSwitch change
    if (pc_reset_switch) {
    digitalWrite(pc_rst_swt, HIGH);
  }
  else {
    digitalWrite(pc_rst_swt, LOW);

  }
}
