// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "ENTER DEVICE ID HERE";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onPcResetSwitchChange();
void onPcSwitchChange();

CloudCounter pc_state_time;
bool disk_state;
bool pc_reset_switch;
bool pc_state;
bool pc_switch;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(pc_state_time, READ, 20 * SECONDS, NULL);
  ArduinoCloud.addProperty(disk_state, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(pc_reset_switch, READWRITE, ON_CHANGE, onPcResetSwitchChange, 1);
  ArduinoCloud.addProperty(pc_state, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(pc_switch, READWRITE, ON_CHANGE, onPcSwitchChange, 1);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
